# Generated by Django 5.0 on 2024-01-27 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='device',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='checkout_date',
            new_name='return_data',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='condition_at_checkout',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='condition_at_return',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='checkout',
            name='device_name',
            field=models.CharField(default='ok', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='taken_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_information',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
