# Generated by Django 5.0 on 2024-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_checkout_device_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='condition',
            field=models.CharField(choices=[('RETURNED', 'Return Device'), ('NOT_RETURNED', 'Not Return Device')], default='NOT_RETURNED', max_length=20),
        ),
    ]
